name: Build

on:
  - pull_request
  - push

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Upload binary
        uses: actions/upload-artifact@v1
        with:
          name: tmignore
          path: ./dist/tmignore
