name: Lint

on:
  - pull_request
  - push

jobs:
  lint:
    name: Lint
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: brew install swiftlint swiftformat

      - name: Lint
        run: |
          swiftlint
          swiftformat .
