name: Lint

on:
  - push
  - pull_request

jobs:
  run-linters:
    name: Run linters
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install linters
        run: brew install swiftlint swiftformat

      - name: Run linters
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          auto_fix: ${{ github.event_name == 'pull_request' }}
          swiftlint: true
          swiftformat: true
