name: Release

on:
  push:
    tags: v*.*.*

jobs:
  release:
    name: Release Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: tmignore
          homebrew-tap: samuelmeuli/homebrew-tap
          commit-message: Release `tmignore` {{version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
