name: Release

on:
  - push
  - pull_request

jobs:
  release-github:
    name: Release on GitHub
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Upload binary to workflow run
        uses: actions/upload-artifact@v1
        with:
          name: tmignore
          path: ./bin/tmignore

      - name: Create GitHub release
        if: startsWith(github.ref, 'refs/tags/v') # Only run on tags
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Upload binary to release
        if: startsWith(github.ref, 'refs/tags/v') # Only run on tags
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/tmignore
          asset_name: tmignore
          asset_content_type: application/octet-stream

  release-homebrew:
    name: Release on Homebrew
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/v') # Only run on tags

    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: tmignore
          homebrew-tap: samuelmeuli/homebrew-tap
          commit-message: Release `tmignore` v{{version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
